#!/usr/bin/env Rscript

# ==============================================================================
# Check and plot sample sex based on X chromosome heterozygosity.
#
# Usage:
#     Rscript 02_check_sex.r <preqcdir> <para> <threshold>
#
# Logic:
#     - Read the .sexcheck file generated by PLINK.
#     - Identify individuals with ambiguous sex (F between 0.2 and 0.8) or mismatched sex.
#     - Generate a scatter plot of F statistic by reported sex.
#
# Outputs:
#     <preqcdir>/<para>_sexcheck.pdf - Scatter plot of sex check results.
#     <preqcdir>/<para>_sex_mismatch_F0.20_M0.80.indvlist - List of mismatched/ambiguous samples.
# ==============================================================================

args <- commandArgs(TRUE)
preqcdir <- args[1]
para <- args[2]
f_threshold <- as.numeric(args[3])
m_threshold <- 1 - f_threshold

setwd(preqcdir)
library(ggplot2)


# Read in data
imp_sex <- read.table(paste0(para, ".chrX.sexcheck"), header = TRUE)

# Assign labels to factor levels
imp_sex$PEDSEX <- factor(imp_sex$PEDSEX, levels = c(1, 2), labels = c("Male", "Female"))
imp_sex$SNPSEX <- factor(imp_sex$SNPSEX, levels = c(0, 1, 2), labels = c("Unknown", "Male", "Female"))


# Plot F-stat distribution: histogram
p <- ggplot(imp_sex, aes(x = F, fill = SNPSEX)) +
    geom_histogram(alpha = 0.6, binwidth = 0.02, color = "black") +
    geom_vline(xintercept = 0.8, linetype = "dashed") + #default cutoff: >0.8: male
    geom_vline(xintercept = 0.2, linetype = "dashed") + #default cutoff: <0.2: female
    theme_bw() +
    labs(x = 'F-statistic', y = 'Frequency', fill = 'Imputed sex') +
    scale_fill_manual(values = c("grey30", "#56B4E9", "#FD8D3C"), labels = c("Unknown", "Male", "Female"))

ggsave(paste0(para, "_sexcheck_Fstat_F02_M08.pdf"), p, width = 7.5, height = 4)


# Plot: imputed vs. reported gender
pdf(paste0(para, "_sexcheck_Fstat_F02_M08_pedsex_vs_snpsex.pdf"), width = 7.5, height = 5)
ggplot(imp_sex, aes(y = F, x = factor(SNPSEX), color = factor(SNPSEX))) +
    geom_jitter(alpha = 0.7) +
    labs(x = 'Imputed Gender', y = 'F-statistic', color = 'Imputed Gender') +
    scale_color_manual(values = c("#7F7F7FFF","#56B4E9","#FD8D3C")) +
    theme_bw()

ggplot(imp_sex, aes(y = F, x = factor(SNPSEX), color = factor(PEDSEX))) +
    geom_jitter(alpha = 0.7) +
    labs(x = 'Imputed Gender', y = 'F-statistic', color = 'Reported Gender') +
    scale_color_manual(values = c("#56B4E9","#FD8D3C")) +
    theme_bw()

dev.off()


# Write out a list of sex discordant samples for removal
sex_mismatch_F02_M08_indv <- imp_sex[(imp_sex$STATUS=="PROBLEM"), c("FID","IID")]

imp_sex$PEDSEX <- as.character(imp_sex$PEDSEX)
imp_sex$SNPSEX <- as.character(imp_sex$SNPSEX)
imp_sex$SNPSEX <- ifelse(imp_sex$F > m_threshold, "Male", imp_sex$SNPSEX)
imp_sex$SNPSEX <- ifelse(imp_sex$F < f_threshold, "Female", imp_sex$SNPSEX)
sex_mismatch_indv <- imp_sex[imp_sex$SNPSEX != imp_sex$PEDSEX, c("FID","IID")]

write.table(sex_mismatch_indv, paste0(para, "_sex_mismatch_F0.", f_threshold*100, "_M0.", m_threshold*100, ".indvlist"), quote = F, col.names = F, row.names = F)
