#!/usr/bin/env Rscript

# ==============================================================================
# Generate PCA plots and perform Random Forest population prediction.
#
# Usage:
#     Rscript 05_pca.r <pcadir> <para> <do_prediction> <color_code_script>
#
# Logic:
#     - Read eigenvalues and eigenvectors generated by PLINK PCA.
#     - If `do_prediction` is TRUE, train a Random Forest classifier on 1kGP reference samples.
#     - Predict the super-population (e.g., EAS) for the study samples.
#     - Generate PCA scatter plots (PC1 vs PC2, PC1 vs PC3) color-coded by population.
#
# Outputs:
#     <pcadir>/<para>_pca.pdf - PCA scatter plots.
#     <pcadir>/<para>_ref_predpop0.8_EAS.indvlist - List of samples predicted as EAS with >80% probability.
# ==============================================================================

args <- commandArgs(TRUE)
pcadir       <- args[1]
para         <- args[2]
EAS_pred     <- args[3]
color_script <- args[4]

npc       <- 6
pred_prob <- 0.8

setwd(pcadir)
library(tidyverse)
library(ggsci)
library(colorspace)
library(randomForest)

source(color_script)

# ── Identify twb1 or twb2 ────────────────────────────────────────────────
batch_num <- sub("twb", "", tolower(para))
id_col    <- paste0("TWB", batch_num, "_ID")

# ── Read ancestry ─────────────────────────────────────────────────────
origin <- read.csv(
  "/staging/reserve/jacobhsu/TWB/TWBR11106-05/Phenotypes_TX/twb_data_cleaning/twb_ancestry/processed_origin.csv",
  stringsAsFactors = FALSE
)
origin_sub <- origin[, c(id_col, "NATIVE_COMBINE")]
names(origin_sub) <- c("IID", "ancestry")

# ── Read 1kGP pedigree ───────────────────────────────────────────────
ped <- read.table(
  "/staging/reserve/jacobhsu/TWB/TWBR11106-05/Phenotypes_TX/1kGP_high_cov/pedigree/20130606_g1k_3202_samples_ped_population.txt",
  header = TRUE, sep = " ", stringsAsFactors = FALSE
)

# ── Helper: ancestry colors ─────────────────────────────────────────────
get_ancestry_colors <- function(ancestries) {
  present <- intersect(ancestry_custom_order, unique(ancestries))
  list(levels = present, colors = ancestry_colors[present])
}

# ── Helper: plot ──────────────────────────────────────────────────────
plot_pca <- function(df, colors) {
  for (ii in 1:5) {
    p <- ggplot(df, aes_string(x = paste0("PC", ii), y = paste0("PC", ii + 1))) +
      geom_point(aes(color = color_group), alpha = 0.7, size = 0.97) +
      scale_color_manual(values = colors) +
      theme_bw() +
      theme(legend.position  = "bottom",
            legend.title     = element_blank(),
            legend.text      = element_text(size = 7),
            legend.key.size  = unit(0.4, "cm")) +
      guides(color = guide_legend(override.aes = list(size = 2), nrow = 5)) +
      labs(x = paste0("PC", ii), y = paste0("PC", ii + 1), color = "Group")
    print(p)
  }
}

# ── Helper: EAS-only plot ──────────────────────────────────────────────────────
plot_pca_eas_only <- function(df, colors) {
  df_1kg <- df %>% filter(!is.na(Population))
  
  for (ii in 1:5) {
    pc_x <- paste0("PC", ii)
    pc_y <- paste0("PC", ii + 1)
    
    # 計算每個 population 的中心點 + offset 到橢圓邊緣外
    centroids <- df_1kg %>%
      group_by(color_group) %>%
      summarise(cx = mean(.data[[pc_x]]),
                cy = mean(.data[[pc_y]]),
                sy = sd(.data[[pc_y]]),
                .groups = "drop") %>%
      mutate(
        x = cx,
        y = cy + 1.96 * sy * 1.2  # 只往上 offset
      )
    
    p <- ggplot(df, aes_string(x = pc_x, y = pc_y)) +
      geom_point(aes(color = color_group), alpha = 0.7, size = 0.97) +
      stat_ellipse(data = df_1kg,
                   aes(color = color_group),
                   level = 0.95, linewidth = 0.6, show.legend = FALSE) +
      geom_text(data = centroids,
                aes(x = x, y = y, label = color_group, color = color_group),
                size = 4, fontface = "bold",
                show.legend = FALSE) +
      scale_color_manual(values = colors) +
      theme_bw() +
      theme(legend.position  = "bottom",
            legend.title     = element_text(size = 8),
            legend.text      = element_text(size = 7),
            legend.key.size  = unit(0.4, "cm")) +
      guides(color = guide_legend(override.aes = list(size = 2), nrow = 5)) +
      labs(x = pc_x, y = pc_y, color = "Group")
    print(p)
  }
}

# ── Helper: iteratively remove outliers ──────────────────────────────────────────
remove_outliers <- function(df, pcs, sd_thresh = 6) {
  repeat {
    thr <- lapply(pcs, function(pc) {
      list(pc    = pc,
           lower = mean(df[[pc]], na.rm = TRUE) - sd_thresh * sd(df[[pc]], na.rm = TRUE),
           upper = mean(df[[pc]], na.rm = TRUE) + sd_thresh * sd(df[[pc]], na.rm = TRUE))
    })
    is_out <- rowSums(sapply(thr, function(t)
      df[[t$pc]] < t$lower | df[[t$pc]] > t$upper)) > 0
    if (sum(is_out) == 0) break
    df <- df[!is_out, ]
  }
  df
}

pcs <- paste0("PC", 1:6)

# ════════════════════════════════════════════════════════════════════════
# PART 1: Study-only PCA
# ════════════════════════════════════════════════════════════════════════
pca <- read.table(paste0(para, "_pca.eigenvec"),
                  header = TRUE, sep = "\t",
                  stringsAsFactors = FALSE, comment.char = "")
names(pca) <- gsub("X\\.", "", names(pca))

pca <- pca %>%
  left_join(origin_sub, by = "IID") %>%
  filter(!is.na(ancestry))

# Set colors
anc <- get_ancestry_colors(pca$ancestry)
pca$color_group <- factor(pca$ancestry, levels = anc$levels)

# Plot (including outliers)
pdf(paste0(para, "_QC_PCA.pdf"), width = 7.5, height = 6)
plot_pca(pca, anc$colors)
dev.off()

# Remove outliers (mean ± 6SD)
is_outlier <- rowSums(
  sapply(pcs, function(pc) {
    m <- mean(pca[[pc]], na.rm = TRUE)
    s <- sd(pca[[pc]], na.rm = TRUE)
    pca[[pc]] < m - 6 * s | pca[[pc]] > m + 6 * s
  })
) > 0

pca_clean <- pca[!is_outlier, ]

write.table(pca[is_outlier, c("FID", "IID")],
            file      = paste0(para, "_PC_6sd_remove.indvlist"),
            quote     = FALSE, row.names = FALSE,
            col.names = FALSE, sep = "\t")

write.table(pca_clean[, c("FID", "IID")],
            file      = paste0(para, "_PC_6sd_keep.indvlist"),
            quote     = FALSE, row.names = FALSE,
            col.names = FALSE, sep = "\t")

# ════════════════════════════════════════════════════════════════════════
# PART 2: Ref PCA (using clean TWB)
# ════════════════════════════════════════════════════════════════════════
pca_ref_raw <- read.table(paste0(para, "_ref_pca.eigenvec"),
                           header = TRUE, sep = "\t",
                           stringsAsFactors = FALSE, comment.char = "")
names(pca_ref_raw) <- gsub("X\\.", "", names(pca_ref_raw))

pca_ref_raw <- merge(pca_ref_raw,
                     ped[, c("SampleID", "Population", "Superpopulation")],
                     by.x = "IID", by.y = "SampleID", all.x = TRUE)

# Separate 1kGP ref and TWB
pca_1kg <- pca_ref_raw %>%
  filter(!is.na(Superpopulation)) %>%
  mutate(color_group = Population,
         pop_label   = Superpopulation)

pca_twb_ref <- pca_ref_raw %>%
  filter(IID %in% pca_clean$IID) %>%
  left_join(origin_sub, by = "IID") %>%
  mutate(color_group = ancestry,
         pop_label   = "TWB")

pca_all <- bind_rows(pca_1kg, pca_twb_ref)

# Colors
anc_ref      <- get_ancestry_colors(pca_twb_ref$ancestry)
present_pops <- intersect(names(pop_colors), unique(pca_1kg$Population))
all_colors   <- c(anc_ref$colors, pop_colors[present_pops])
pca_all$color_group <- factor(pca_all$color_group,
                               levels = c(anc_ref$levels, present_pops))

# Iteratively remove outliers
# pca_all <- remove_outliers(pca_all, pcs)

# All samples plot
pdf(paste0(para, "_ref_QC_PCA.pdf"), width = 10.5, height = 6)
plot_pca(pca_all, all_colors)
dev.off()

# EAS + TWB plot (extracted from the full ref PCA, PC space is calculated from the full set)
pca_eas     <- pca_all %>% filter(pop_label %in% c("TWB", "EAS"))
eas_pops    <- intersect(pop_groups$EAS, as.character(unique(pca_eas$color_group)))
eas_colors  <- c(anc_ref$colors, pop_colors[eas_pops])
pca_eas$color_group <- factor(pca_eas$color_group,
                               levels = c(anc_ref$levels, eas_pops))

# Remove outliers (mean ± 6SD)
pca_eas <- remove_outliers(pca_eas, pcs)

pdf(paste0(para, "_ref_EAS_QC_PCA.pdf"), width = 10, height = 6)
plot_pca(pca_eas, eas_colors)
dev.off()

# ════════════════════════════════════════════════════════════════════════
# PART 3: EAS ancestry prediction
# ════════════════════════════════════════════════════════════════════════
if (EAS_pred == "TRUE") {
  print("Predict EAS ancestry for study samples")

  print(paste0("Use RF to predict ancestry based on top ", npc, " PCs"))

  pop_forest <- function(training_data, data, ntree = 100, seed = 42, pcs = 1:npc) {
    set.seed(seed)
    form <- formula(paste("as.factor(known_pop) ~",
                          paste0("PC", pcs, collapse = " + ")))
    forest <- randomForest(form, data = training_data, importance = TRUE, ntree = ntree)
    print(forest)
    fit_data <- data.frame(predict(forest, data, type = "prob"), sample = data$sample)
    fit_data %>%
      gather(predicted_pop, probability, -sample) %>%
      group_by(sample) %>%
      slice(which.max(probability))
  }

  trdat <- pca_1kg %>%
    select(Superpopulation, PC1:PC10) %>%
    rename(known_pop = Superpopulation)
  trdat$known_pop <- as.character(trdat$known_pop)

  tedat <- pca_twb_ref %>%
    select(IID, PC1:PC10)
  names(tedat)[1] <- "sample"
  tedat$sample <- as.character(tedat$sample)

  print("Prediction results:")
  pop_pred <- as.data.frame(pop_forest(training_data = trdat, data = tedat))

  print("Overall ancestry assignment:")
  print(table(pop_pred$predicted_pop))

  print(paste0("Subset to prediction prob. > ", pred_prob, ":"))
  pop_pred.sub <- pop_pred %>% filter(probability > pred_prob)
  print(table(pop_pred.sub$predicted_pop))

  names(pop_pred)[1] <- "IID"
  pca.pred     <- left_join(pca_twb_ref, pop_pred, by = "IID")
  pca.pred$predicted_pop <- factor(pca.pred$predicted_pop,
                                    levels = c("AFR", "AMR", "EAS", "EUR", "SAS"))
  pca.pred.sub <- pca.pred %>% filter(probability >  pred_prob)
  pca.nonpred  <- pca.pred %>% filter(probability <= pred_prob)

  write.table(pca.pred, paste0(para, "_ref_predpop.tsv"),
              quote = FALSE, col.names = TRUE, row.names = FALSE, sep = "\t")

  eas_indv     <- pca.pred.sub %>% filter(predicted_pop == "EAS") %>% select(FID, IID)
  non_eas_indv <- pca.nonpred %>% select(FID, IID)
  write.table(eas_indv,
              paste0(para, "_ref_predpop", pred_prob, "_EAS.indvlist"),
              quote = FALSE, col.names = FALSE, row.names = FALSE, sep = "\t")
  write.table(non_eas_indv,
              paste0(para, "_ref_nonpredpop.indvlist"),
              quote = FALSE, col.names = FALSE, row.names = FALSE, sep = "\t")

  # ════════════════════════════════════════════════════════════════════════
  # PART 4: EAS-only PCA (re-run PC restricted to EAS)
  # ════════════════════════════════════════════════════════════════════════
  pca_eas_only <- read.table(paste0(para, "_EAS_pca.eigenvec"),
                              header = TRUE, sep = "\t",
                              stringsAsFactors = FALSE, comment.char = "")
  names(pca_eas_only) <- gsub("X\\.", "", names(pca_eas_only))

  pca_eas_only <- merge(pca_eas_only,
                        ped[, c("SampleID", "Population", "Superpopulation")],
                        by.x = "IID", by.y = "SampleID", all.x = TRUE)

  pca_eas_1kg <- pca_eas_only %>%
    filter(!is.na(Superpopulation)) %>%
    mutate(color_group = Population)

  pca_eas_twb <- pca_eas_only %>%
    filter(is.na(Superpopulation)) %>%
    left_join(origin_sub, by = "IID") %>%
    mutate(color_group = ancestry)

  pca_eas_only <- bind_rows(pca_eas_1kg, pca_eas_twb)

  # Colors
  anc_eas         <- get_ancestry_colors(pca_eas_twb$ancestry)
  eas_pops_only   <- intersect(pop_groups$EAS, unique(pca_eas_1kg$Population))
  eas_only_colors <- c(anc_eas$colors, pop_colors[eas_pops_only])
  pca_eas_only$color_group <- factor(pca_eas_only$color_group,
                                      levels = c(anc_eas$levels, eas_pops_only))

  # Iteratively remove outliers
  # pca_eas_only <- remove_outliers(pca_eas_only, pcs)

  # Plot
  pdf(paste0(para, "_EAS_only_PCA.pdf"), width = 10, height = 6)
  plot_pca_eas_only(pca_eas_only, eas_only_colors)
  dev.off()

} else {
  print("Skip EAS ancestry prediction")
}
