# ==============================================================================
# Combine, sort, and visualize PRSice-2 summary results.
#
# Usage:
#     Rscript 06_sort_table.r
#
# Logic:
#     - Recursively read all .summary files generated by PRSice-2 for SV+SNV and SNV panels.
#     - Compile the results across multiple quantitative phenotypes.
#     - Calculate Incremental R^2 (Full R^2 - Null R^2).
#     - Pivot data into long-format and wide-format tables for comparative analysis.
#     - Compute Delta Incremental R^2 (SV+SNV minus SNV) to measure SV contribution.
#     - Generate a grouped bar chart visualizing the comparison.
#
# Outputs:
#     <outdir>/PRS_summary_long.tsv - Long-format summary table.
#     <outdir>/PRS_summary_wide.tsv - Wide-format comparison table.
#     <outdir>/PRS_incremental_R2.pdf - Grouped bar chart of Incremental R^2 by phenotype.
# ==============================================================================

library(data.table)
library(dplyr)
library(ggplot2)

# ── Phenotype list ─────────────────────────────────────────────────────────────
phenotypes <- c(
  "BODY_HEIGHT", "BODY_WEIGHT", "BMI", "BODY_FAT_RATE",
  "BODY_WAISTLINE", "BODY_BUTTOCKS", "WHR",
  "T_SCORE", "Z_SCORE",
  "FVC", "FEV1", "FEV1_FVC",
  "SYSTOLIC_PRESSURE", "DIASTOLIC_PRESSURE", "HEARTBEAT_SPEED",
  "RBC", "WBC", "HB", "HCT", "PLATELET",
  "HBA1C", "AC_GLUCOSE",
  "T_CHO", "TG", "HDL_C", "LDL_C",
  "T_BILIRUBIN", "ALBUMIN", "SGOT", "SGPT", "GAMMA_GT", "AFP",
  "BUN", "CREATININE", "URIC_ACID",
  "MICROALB", "CREATININE_URINE", "EGFRcr"
)

# ── Directory paths ────────────────────────────────────────────────────────────
out_dir <- Sys.getenv("OUT_DIR")
if (out_dir == "") out_dir <- "/staging/biology/u4432941/sv/prs/outputs"

dir_sv_snv <- file.path(out_dir, "prsice", "sv_snv.quan")
dir_snv    <- file.path(out_dir, "prsice", "snv.quan")
outdir     <- file.path(out_dir, "prsice", "comparison")
if (!dir.exists(outdir)) dir.create(outdir, recursive = TRUE)

# ── Helper: read a single .summary file ───────────────────────────────────────
read_summary <- function(dir, phenotype, prs_type) {
  path <- file.path(dir, paste0(phenotype, ".summary"))

  if (!file.exists(path)) {
    warning(sprintf("[MISSING] %s | %s -> %s", prs_type, phenotype, path))
    return(NULL)
  }

  dt <- tryCatch(
    fread(path),
    error = function(e) {
      warning(sprintf("[READ ERROR] %s | %s: %s", prs_type, phenotype, e$message))
      return(NULL)
    }
  )

  if (is.null(dt) || nrow(dt) == 0) return(NULL)

  dt[, `:=`(Phenotype = phenotype, PRS_type = prs_type)]
  return(dt)
}

# ── Read all summary files ─────────────────────────────────────────────────────
cat("Reading summary files...\n")

all_records <- rbindlist(
  c(
    lapply(phenotypes, read_summary, dir = dir_sv_snv, prs_type = "SV_SNV"),
    lapply(phenotypes, read_summary, dir = dir_snv,    prs_type = "SNV")
  ),
  fill = TRUE
)

if (nrow(all_records) == 0) stop("No summary files were successfully read.")

cat(sprintf("Loaded %d records across %d phenotypes.\n",
            nrow(all_records), length(unique(all_records$Phenotype))))

# ── Compute incremental R² ─────────────────────────────────────────────────────
all_records[, Incremental_R2 := Full.R2 - Null.R2]

# ── Long-format table ─────────────────────────────────────────────────────────
result_long <- all_records[, .(
  Phenotype      = Phenotype,
  PRS_type       = PRS_type,
  Best_Threshold = Threshold,
  Null_R2        = round(Null.R2,        4),
  Full_R2        = round(Full.R2,        4),
  Incremental_R2 = round(Incremental_R2, 4),
  PRS_R2         = round(PRS.R2,         4),
  Coefficient    = round(Coefficient,    4),
  SE             = round(Standard.Error, 4),
  P_value        = P,
  Num_SNP        = Num_SNP
)]

result_long[, Phenotype := factor(Phenotype, levels = phenotypes)]
setorder(result_long, Phenotype, PRS_type)

# ── Wide-format table ─────────────────────────────────────────────────────────
result_wide <- dcast(
  result_long,
  Phenotype ~ PRS_type,
  value.var = c("Best_Threshold", "Null_R2", "Full_R2",
                "Incremental_R2", "PRS_R2", "Num_SNP", "P_value", "Coefficient")
)

result_wide[, Delta_Incremental_R2 := round(Incremental_R2_SV_SNV - Incremental_R2_SNV, 4)]
setorder(result_wide, -Delta_Incremental_R2)

# ── Save tables ───────────────────────────────────────────────────────────────
fwrite(result_long, file.path(outdir, "PRS_summary_long.tsv"),  sep = "\t")
fwrite(result_wide, file.path(outdir, "PRS_summary_wide.tsv"),  sep = "\t")
cat(sprintf("\nTables written to %s\n", outdir))

# ── Console summary ───────────────────────────────────────────────────────────
cat("\n── Top phenotypes by ΔIncremental R² (SV+SNV − SNV) ──\n")
print(result_wide[, .(Phenotype, Incremental_R2_SNV, Incremental_R2_SV_SNV,
                       Delta_Incremental_R2, Num_SNP_SNV, Num_SNP_SV_SNV)][1:10])

found   <- unique(as.character(result_long$Phenotype))
missing <- setdiff(phenotypes, found)
if (length(missing) > 0) {
  cat(sprintf("\n[WARNING] %d phenotype(s) missing:\n", length(missing)))
  cat(paste(" -", missing, collapse = "\n"), "\n")
} else {
  cat("\nAll phenotypes loaded successfully.\n")
}

# ── Visualization ─────────────────────────────────────────────────────────────

# Build wide table for delta labels
wide <- dcast(result_long, Phenotype ~ PRS_type, value.var = "Incremental_R2")
wide[, Delta := round(SV_SNV - SNV, 4)]

# Long format for grouped bars
plot_df <- melt(wide, id.vars = c("Phenotype", "Delta"),
                measure.vars = c("SNV", "SV_SNV"),
                variable.name = "Type", value.name = "R2")

# Sort bars by SV_SNV R² descending
ord <- wide[order(-SV_SNV), Phenotype]
plot_df[, Phenotype := factor(Phenotype, levels = rev(ord))]
wide[,   Phenotype := factor(Phenotype, levels = rev(ord))]

# Label data: placed at the tip of the SV_SNV bar
# Show delta as "+0.0012" or "-0.0003"; omit if delta is NA
label_df <- wide[!is.na(Delta), .(
  Phenotype = Phenotype,
  x         = SV_SNV,          # position along x-axis (tip of SV_SNV bar)
  label     = ifelse(Delta >= 0,
                     sprintf("+%.4f", Delta),
                     sprintf("%.4f",  Delta)),
  color     = ifelse(Delta >= 0, "pos", "neg")
)]

plt <- ggplot(plot_df, aes(x = R2, y = Phenotype, fill = Type)) +

  # Grouped bars
  geom_col(position = position_dodge(0.7), width = 0.6, na.rm = TRUE) +

  # Delta labels at tip of SV_SNV bar
  # dodge offset = 0.35 puts us at the SV_SNV bar (top of the pair)
  geom_text(
    data = label_df,
    aes(x = x, y = Phenotype, label = label, color = color),
    position  = position_dodge(0.7),   # aligns with SV_SNV bar
    hjust     = -0.15,                 # just outside the bar tip
    vjust     = -0.6,                  # shift up to sit on SV_SNV bar
    size      = 2.8,
    inherit.aes = FALSE
  ) +

  scale_fill_manual(
    values = c(SNV = "#378ADD", SV_SNV = "#1D9E75"),
    labels = c("SNV", "SV+SNV")
  ) +
  scale_color_manual(
    values = c(pos = "#0F6E56", neg = "#993C1D"),
    guide  = "none"   # hide the color legend for delta labels
  ) +

  # Expand x-axis right so labels aren't clipped
  scale_x_continuous(expand = expansion(mult = c(0, 0.18))) +

  labs(
    x     = expression(paste("Incremental R"^2)),
    y     = NULL,
    fill  = NULL,
    title = expression(paste("PRS incremental R"^2, " by phenotype")),
    caption = "Labels show \u0394 = SV+SNV \u2212 SNV (green = gain, red = loss)"
  ) +

  theme_bw(base_size = 12) +
  theme(
    legend.position  = "top",
    plot.caption     = element_text(size = 9, color = "grey50", hjust = 0),
    panel.grid.major.y = element_blank()
  )

ggsave(file.path(outdir, "PRS_incremental_R2.pdf"),
       plt, width = 9, height = 11)

cat(sprintf("\nPlot saved to %s\n", outdir))
